### ISSUE TITLE
ValidationはFormリクエストに統一する

### ISSUE THREAD

**Issue by ProjectEuropa** [narumichi0710/Shairechat#2]
https://github.com/narumichi0710/Shairechat/blob/ade00e49eca0a4c482bb0bd7e1c0bb89f0dc4900/app/Http/Controllers/UserController.php#L58-L78

Controllerに存在するパターンとFormRequestに存在するパターンが混在している。
FormRequestに統一した方がスマート

**Comment by narumichi0710** [comment]
フォームリクエストに統一しました。
